apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-name
  labels:
    app: my-app-label
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: simple-node
        image: langerca/udacity-simple-node:latest
        ports:
        - containerPort: 80

