language: generic

os: linux

jobs:
  include:
    services:
     - docker
    script:
      - docker --version # print the version for logging
      - cd ./lesson-2-containers/exercises/simple-node
      - docker build -t simple-node .
      - docker tag simple-node langerca/udacity-simple-node:latest
    after_success:
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - docker push langerca/udacity-simple-node:latest
