language: generic

os: linux

services:
 - docker

jobs:
  include:
    - name: build and upload simple-node docker image
      script:
        - docker --version # print the version for logging
        - cd ./lesson-2-containers/exercises/simple-node
        - docker build -t simple-node .
        - docker tag simple-node langerca/udacity-simple-node:latest
      after_success:
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - docker push langerca/udacity-simple-node:latest

    - name: build and upload simple-express docker image
      script:
        - docker --version # print the version for logging
        - cd ./lesson-5-kubernetes-for-production/exercises/simple-express   
        - docker build -t simple-express .
        - docker tag simple-express langerca/udacity-simple-express:latest
      after_success:
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - docker push langerca/udacity-simple-express:latest

    - name: build and upload ngnix docker image with config for my-app-2-svc
      script:
        - docker --version # print the version for logging
        - cd ./lesson-5-kubernetes-for-production/demos/reverse-proxy
        - docker build -t reverse-proxy-my-app-2-svc .
        - docker tag reverse-proxy-my-app-2-svc langerca/udacity-reverse-proxy-my-app-2-svc:latest
      after_success:
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - docker push langerca/udacity-reverse-proxy-my-app-2-svc:latest


